apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- git@github.com:jadeerp/sample-microservice/k8s/main/sample-depl.yaml
namespace: default
images:
- name: ifextech/jadeerp-stock-service
  newTag: latest